config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#top'
  resources :scraps do
    resources :comments, only: %i[create destroy], shallow: true
  end

  resources :bookmarks, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :scrap
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :scrap

  validates :content, presence: true, length: { maximum: 255 }
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/scrap.rb
# frozen_string_literal: true

class Scrap < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 1000 }

  scope :with_tag, ->(tag_name) { joins(:tags).where(tags: { name: tag_name }) }

  def save_with_tags(tag_names:)
    ActiveRecord::Base.transaction do
      self.tags = tag_names.map { |name| Tag.find_or_initialize_by(name: name.strip) }
      save!
    end
    true
  rescue StandardError
    false
  end

  def tag_names
    tags.map(&:name).join(',')
  end
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :scraps, through: :taggings
end

app/models/tagging.rb
# frozen_string_literal: true

class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :scrap
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :scraps, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_scraps, through: :bookmarks, source: :scrap

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  # =======================================================================================
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true, length: { maximum: 20 }

  def owns?(resource)
    id == resource.user_id
  end

  def bookmark?(resource)
    bookmark_scraps.include?(resource)
  end

  def bookmark(resource)
    bookmark_scraps << resource
  end

  def unbookmark(resource)
    bookmark_scraps.destroy(resource)
  end

  def follow?(resource)
    followings.include?(resource)
  end

  def follow(resource)
    followings << resource
  end

  def unfollow(resource)
    followings.destroy(resource)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/bookmarks_controller.rb
# frozen_string_literal: true

class BookmarksController < ApplicationController
  def create
    @scrap = Scrap.find(params[:scrap_id])
    current_user.bookmark(@scrap)
    flash[:notice] = 'ブックマークに成功しました'
    redirect_to scraps_path
  end

  def destroy
    scrap = current_user.bookmarks.find(params[:id]).scrap
    current_user.unbookmark(scrap)
    flash[:notice] = 'ブックマークの削除に成功しました'
    redirect_to scraps_path
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = current_user.comments.new(comment_params)
    return unless @comment.save

    flash[:notice] = 'コメントの投稿に成功しました'
    redirect_to scrap_path(params[:scrap_id])
  end

  def destroy
    @comment = current_user.comments.find_by(id: params[:id])
    @comment.destroy!
    flash[:notice] = 'コメントの削除に成功しました'
    redirect_to scrap_path(@comment.scrap_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(scrap_id: params[:scrap_id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def top; end
end

app/controllers/relationships_controller.rb
# frozen_string_literal: true

class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
    flash[:notice] = 'フォローに成功しました'
    redirect_to scraps_path
  end

  def destroy
    user = User.find(params[:id])
    current_user.unfollow(user)
    flash[:notice] = 'フォローを外すことに成功しました'
    redirect_to scraps_path
  end
end

app/controllers/scraps_controller.rb
# frozen_string_literal: true

class ScrapsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_scrap, only: %i[show edit update destroy]

  def index
    @scraps = Scrap.includes(:tags).order(created_at: :desc)
  end

  def show
    @comments = @scrap.comments.includes(:user).order(created_at: :desc)
    @comment = Comment.new
  end

  def new
    @scrap = Scrap.new
  end

  def create
    @scrap = current_user.scraps.new(scrap_params)
    if @scrap.save_with_tags(tag_names: params.dig(:scrap, :tag_names).split(',').uniq)
      flash[:notice] = '記録しました'
      redirect_to scraps_path
    else
      flash[:alert] = '記録に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @scrap.assign_attributes(scrap_params)
    if @scrap.save_with_tags(tag_names: params.dig(:scrap, :tag_names).split(',').uniq)
      flash[:notice] = '記録を更新しました'
      redirect_to scraps_path
    else
      flash[:alert] = '記録の更新に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if (@scrap.user = current_user)
      @scrap.destroy
      flash[:notice] = '記録が削除されました'
    end
    redirect_to scraps_path
  end

  private

  def set_scrap
    @scrap = current_user.scraps.find_by(id: params[:id])
  end

  def scrap_params
    params.require(:scrap).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
# frozen_string_literal: true

module BookmarksHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/relationships_helper.rb
# frozen_string_literal: true

module RelationshipsHelper
end

app/helpers/scraps_helper.rb
# frozen_string_literal: true

module ScrapsHelper
end

app/views/bookmarks/_bookmark.html.erb
<div>
  <%= link_to 'ブックマークしてない', bookmarks_path(scrap_id: scrap.id), data: { turbo_method: :post} %>
</div>

app/views/bookmarks/_bookmark_button.html.erb
 <% if user_signed_in? %>
   <% if  current_user.bookmark?(scrap)%>
      <%= render 'bookmarks/unbookmark', { scrap: scrap }%> 
    <% else %>
      <%= render 'bookmarks/bookmark', { scrap: scrap }%> 
    <% end%>
<% end %>

app/views/bookmarks/_unbookmark.html.erb
<div>
  <%= link_to 'ブックマーク済み', bookmark_path(current_user.bookmarks.find_by(scrap_id: scrap.id)), data: { turbo_method: :delete} %>
</div>

app/views/comments/_comment.html.erb
<div tabindex="0" aria-label="card 1" class="focus:outline-none mb-7 bg-white p-6 shadow rounded">
  <div class="flex items-center border-b border-gray-200 pb-6">
    <div class="flex items-start justify-between w-full">
      <div class="pl-3">
        <p class="focus:outline-none text-sm leading-normal pt-2 text-gray-500"><%= comment.content %></p>
        <p class="focus:outline-none text-sm leading-normal pt-2 text-gray-500">by <%= comment.user.nickname %></p>
      </div>
      <% if user_signed_in? %>
        <% if current_user&.owns?(comment) %>
          <%= link_to "削除する", comment_path(comment), data: {turbo_method: :delete}, class: "text-sm bg-transparent hover:bg-blue-500 text-blue-700 hover:text-white py-1 px-3 border border-blue-500 hover:border-transparent rounded" %>
        <% end %>
      <% end %>
      </div>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: comment, url: scrap_comments_path(scrap), class: "w-3/4 max-w-lg mb-3" do |f| %>
  <div class="mt-1">
    <%= f.text_field :content, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm placeholder-gray-400 border border-gray-300 rounded-md", placeholder: "Railsチュートリアル1章を完了" %>
    <%= f.submit "コメントする", class: "inline-block justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
<% end %>

app/views/home/top.html.erb
<div>
  <h1 class="font-bold text-4xl">Home#top</h1>
  <p>Find me in app/views/home/top.html.erb</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lookback</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen bg-slate-100">
  <%= render 'shared/navbar'%>
   <%= render 'shared/flash'%>
    <main class="container mx-auto mt-20 py-8 px-5 flex items-center justify-center">
      <%= yield %>
    </main>
  </body>
</html>

app/views/relationships/_follow.html.erb
<div>
  <%= link_to 'フォローしてない', relationships_path(user_id: scrap.user_id), data: { turbo_method: :post} %>
</div>

app/views/relationships/_follow_button.html.erb
<% if user_signed_in? %>
  <% if current_user.follow?(scrap.user)%>
    <%= render 'relationships/unfollow', { scrap: scrap } %>
  <% else %>
    <%= render 'relationships/follow', { scrap: scrap } %>
  <% end %>
<% end %>

app/views/relationships/_unfollow.html.erb
<div>
  <%= link_to 'フォロー済み', relationship_path(scrap.user_id), data: { turbo_method: :delete} %>
</div>

app/views/scraps/edit.html.erb
<%= form_with model: @scrap, class: "space-y-6 w-3/4 max-w-lg" do |f| %>
    <label class="block text-xl font-bold text-gray-700">スクラップを更新する</label>
    <div class="mt-1">
      <label class="text-gray-700 text-lg">
        タイトル
      </label>
      <%= f.text_field :title, value: @scrap.title, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm placeholder-gray-400 border border-gray-300 rounded-md", placeholder: "Railsチュートリアル1章を完了" %>
    </div>
    <div class="mt-1">
      <label class="text-gray-700 text-lg">
        本文
      </label>
      <%= f.text_area :content,value: @scrap.content,rows: "5", class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm placeholder-gray-400 border border-gray-300 rounded-md", placeholder: "環境構築を無事に終えることができた！" %>
    </div>
    <div class="mt-1">
      <label class="text-gray-700 text-lg">
        タグ
      </label> 
      <%= f.text_field :tag_names, value: @scrap.tags.pluck(:name).join(','), rows: "5", class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm placeholder-gray-400 border border-gray-300 rounded-md", placeholder: ",で区切って入力してください。" %>
    </div>
    <p class="mt-2 text-sm text-gray-500">
      学習したこと、開発したことを記録しましょう。<br>
      参考にしたサイトがあればURLを書いておくことをオススメします。
    </p>
    <div class="px-4 py-3 text-right sm:px-6">
      <%= f.submit "ログを更新", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    </div>
  <% end %>

app/views/scraps/index.html.erb
<div class="space-y-6 w-3/4 max-w-lg">
  <label class="block text-xl font-bold text-gray-700">学習ログ一覧</label>
  <div class="items-center justify-center">
    <% @scraps.each do |scrap| %>
      <div tabindex="0" aria-label="card 1" class="focus:outline-none mb-7 bg-white p-6 shadow rounded">
        <div class="flex items-center border-b border-gray-200 pb-6">
          <div class="flex items-start justify-between w-full">
            <div class="pl-3">
              <p class="focus:outline-none text-lg font-medium leading-5 text-gray-800"><%= link_to scrap.title, scrap_path(scrap) %></p>
              <p class="focus:outline-none text-sm leading-normal pt-2 text-gray-500">by <%= scrap.user.nickname %></p>
            </div>
          </div>
        </div>
        <div class="flex justify-between">
        <div class="px-2">
          <p class="focus:outline-none text-sm leading-5 py-4 text-gray-600"><%= scrap.content %></p>
          <% scrap.tags.each do |tag| %>
          <a><%= tag.name %></a>
          <% end %>
        </div>
        <div class="flex mt-3">
        <div class="px-2">
          <% if current_user&.owns?(scrap) %>
            <button type="button" class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">
              <%= link_to '編集する', edit_scrap_path(scrap) %>
            </button>
          <% end %>
        </div>
        <div class="flex">
          <%= render 'bookmarks/bookmark_button', scrap: scrap %>
          <% if current_user != scrap.user %>
            <%= render 'relationships/follow_button', scrap: scrap %>
          <% end %>
        </div>
      </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/scraps/new.html.erb
<%= form_with model: @scrap, class: "space-y-6 w-3/4 max-w-lg" do |f| %>
  <label class="block text-xl font-bold text-gray-700">ログを記録する</label>
  <div class="mt-1">
    <label class="text-gray-700 text-lg">
      タイトル
    </label>
    <%= f.text_field :title, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm placeholder-gray-400 border border-gray-300 rounded-md", placeholder: "Railsチュートリアル1章を完了" %>
  </div>
  <div class="mt-1">
    <label class="text-gray-700 text-lg">
      本文
    </label> 
    <%= f.text_area :content, rows: "5", class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm placeholder-gray-400 border border-gray-300 rounded-md", placeholder: "環境構築を無事に終えることができた！" %>
  </div>
  <div class="mt-1">
    <label class="text-gray-700 text-lg">
      タグ
    </label> 
    <%= f.text_field :tag_names, rows: "5", class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm placeholder-gray-400 border border-gray-300 rounded-md", placeholder: ",で区切って入力してください。" %>
  </div>
  <p class="mt-2 text-sm text-gray-500">
    学習したこと、開発したことを記録しましょう。<br>
    参考にしたサイトがあればURLを書いておくことをオススメします。
  </p>
  <div class="px-4 py-3 text-right sm:px-6">
    <%= f.submit "ログを記録", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
<% end %>

app/views/scraps/show.html.erb
<div class="space-y-6 w-3/4 max-w-lg">
  <label class="block text-xl font-bold text-gray-700">学習ログ詳細</label>
  <div class="items-center justify-center">
      <div tabindex="0" aria-label="card 1" class="focus:outline-none mb-7 bg-white p-6 shadow rounded">
        <div class="flex items-center border-b border-gray-200 pb-6">
          <div class="flex items-start justify-between w-full">
            <div class="pl-3">
              <p class="focus:outline-none text-lg font-medium leading-5 text-gray-800"><%= link_to @scrap.title, scrap_path(@scrap) %></p>
              <p class="focus:outline-none text-sm leading-normal pt-2 text-gray-500">by <%= @scrap.user.nickname %></p>
            </div>
            <% if user_signed_in? %>
              <% if current_user&.owns?(@scrap) %>
                <%= button_to "削除する", scrap_path(@scrap), method: :delete, class: "text-sm bg-transparent hover:bg-blue-500 text-blue-700 hover:text-white py-1 px-3 border border-blue-500 hover:border-transparent rounded" %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="px-2">
          <p class="focus:outline-none text-sm leading-5 py-4 text-gray-600"><%= @scrap.content %></p>
        </div>
      </div>

      <%= render 'comments/form', comment: @comment, scrap: @scrap %>
      <%= render @comments %>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="p-4 mt-3 mb-4 mx-3 text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-blue-200 dark:text-blue-800" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="p-4 mt-3 mb-4 mx-3 text-sm text-red-700 bg-red-100 rounded-lg dark:bg-red-200 dark:text-red-800" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="bg-gray-800 border-gray-200 px-2 sm:px-4 py-2.5">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <%= link_to "LookBack", "/", class: "self-center text-white text-xl font-semibold whitespace-nowrap" %>
    <div class="w-full md:block md:w-auto">
      <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
        <% if current_user %>
          <li>
            <%= link_to "ログ一覧", scraps_path, class: "block py-2 pr-4 pl-3 text-gray-400 hover:text-white border-b border-gray-700 hover:bg-gray-700 md:hover:bg-transparent md:border-0 md:hover:text-blue-white md:p-0" %>
          </li>
          <li>
            <%= link_to "ログ投稿", new_scrap_path, class: "block py-2 pr-4 pl-3 text-gray-400 hover:text-white border-b border-gray-700 hover:bg-gray-700 md:hover:bg-transparent md:border-0 md:hover:text-blue-white md:p-0" %>
          </li>
          <li>
            <%= button_to "ログアウト", destroy_user_session_path, class: "block py-2 pr-4 pl-3 text-gray-400 hover:text-white border-b border-gray-700 hover:bg-gray-700 md:hover:bg-transparent md:border-0 md:hover:text-blue-white md:p-0", method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "ログ一覧", scraps_path, class: "block py-2 pr-4 pl-3 text-gray-400 hover:text-white border-b border-gray-700 hover:bg-gray-700 md:hover:bg-transparent md:border-0 md:hover:text-blue-white md:p-0" %>
          </li>
          <li>
            <%= link_to "ユーザー登録", new_user_registration_path, class: "block py-2 pr-4 pl-3 text-gray-400 hover:text-white border-b border-gray-700 hover:bg-gray-700 md:hover:bg-transparent md:border-0 md:hover:text-blue-white md:p-0" %>
          </li>
          <li>
            <%= link_to "ログイン", new_user_session_path, class: "block py-2 pr-4 pl-3 text-gray-400 hover:text-white border-b border-gray-700 hover:bg-gray-700 md:hover:bg-transparent md:border-0 md:hover:text-blue-white md:p-0" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>